// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FSharpx.Async")>]
[<assembly: AssemblyProductAttribute("FSharpx.Async")>]
[<assembly: AssemblyDescriptionAttribute("Async extensions for F#")>]
[<assembly: AssemblyVersionAttribute("1.14.0")>]
[<assembly: AssemblyFileVersionAttribute("1.14.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FSharpx.Async"
    let [<Literal>] AssemblyProduct = "FSharpx.Async"
    let [<Literal>] AssemblyDescription = "Async extensions for F#"
    let [<Literal>] AssemblyVersion = "1.14.0"
    let [<Literal>] AssemblyFileVersion = "1.14.0"
