language: csharp

mono: 5.2.0
dotnet: 2.2.203

install:
  - mozroots --import --sync
  - export FrameworkPathOverride=$(dirname $(which mono))/../lib/mono/4.5/
matrix:
  include:
    - os: linux # Ubuntu 14.04
      dist: trusty
      sudo: required
      dotnet: 2.2.203
    - os: osx # OSX 10.12
      osx_image: xcode9.1
      dotnet: 2.2.203
      dist: trusty
      sudo: required

script: 
  - ./build.sh All

branches:
  except:
    - gh-pages
