environment:
  CLI_VERSION: 2.2.203
image: Visual Studio 2019
init:
  - git config --global core.autocrlf input
build_script:
  - cmd: build.cmd All
test: off
version: '{build}'
artifacts:
  - path: bin/FSharpx.Async.*.nupkg
    name: nupkg
